### ISSUE TITLE
Parsing the downloadRecording response

### ISSUE THREAD

**Issue by sloan58** [rsathishtechit/webex#1]
Hi,

Thanks for the great package!

I'm using this package to pull down recordings from the NBR API and so far all is working very well.  I'm now moving to parse the response from the downloadRecording method and I know that you've mentioned using the multi-part parser package and was wondering if you happen to have any sample code for this?

I'm working through it now but thought I'd check to see if you've had success already and might be able to give a head start on working with the response.  I'm able to download and save the raw response but it has the rest of the XML included, which I'd like to eliminate in a clean way.

Right now when I call `var_dump($document->isMultiPart());` on the response I get `false`

Thanks for any tips you can provide!

**Comment by rsathishtechit** [comment]
Sorry for the delay. Still you are looking for sample code?. Basically after parsing using the multi-part package, you might have multiple arrays in result. In that list, one array might have the recording name and the other one has actual content of the recording. Here you have to save the content using filename. This is how I have created the local copy of the recording.

**Comment by rsathishtechit** [comment]
Please refer the below commit for Parsing download response.

https://github.com/rsathishtechit/webex/commit/21d02aef0e250cbb0665a845fc1dc67b62d78bc5

**Comment by sloan58** [comment]
Thanks, @rsathishtechit!  Sorry I didn't get back to you on this.  I ended up going a different route with Python to get the downloads but I will try this out as well since I'd rather stick with this PHP package.  I appreciate the point in the right direction.
